upstream:
  prometheus:
    url: http://localhost:9090
  alertmanager:
    url: http://localhost:9093
  servicegraph:
    url: http://localhost:9090

mapping:
  # this defines how we select alerts to display
  # use a `labelSelector` to filter
  # and `map` to specify the lookup key in the alert struct
  alerts:
    labelSelector:
      - severity: "critical"
      - severity: "warning"
        important: "true"
    map:
      label: "service_id"

  # this helps us to find all existing services by fetching the label values
  # reference: https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values
  service_labels:
    - 'service_id'

  metrics:
    queries:
      # just as an example
      - name: CPU
        query: sum(rate(node_cpu_seconds_total[1m])) by (service_id)
        service_label: service_id
      - name: CPU
        query: sum(rate(node_cpu_seconds_total[1m])) by (service_id)
        service_label: service_id
